spring.application.name=CosmeticShop

# Kết nối MySQL XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/sarah_cosmetics_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate tự động tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Giới hạn kích thước file upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Đường dẫn thư mục lưu ảnh cục bộ trên máy chủ
app.upload.dir=uploads/
# Cấu hình Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vvzom123@gmail.com
spring.mail.password=rtru ouxy ihdi mbsp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# JWT Configuration (Key 256-bit chuẩn HMAC-SHA)
app.jwt.secret=9a4f2c8d3b7a1e6f5c8d0b2a4e6f8a1c3d5e7b9a2c4d6f8e0b1a3c5d7e9f1a2b
app.jwt.expiration-ms=86400000